# =========================
# Application
# =========================
spring.application.name=accountingService
spring.profiles.active=${PROFIL:local}
server.servlet.context-path=/api/accounting

# =========================
# Actuator
# =========================
management.endpoints.web.exposure.include=health,info,metrics

# =========================
# Config Server
# =========================
spring.config.import=optional:configserver:${HOST_CONFIG:http://localhost}:8888
