spring.application.name=authService
spring.profiles.active=${PROFIL:local}
server.servlet.context-path=/api/auth

management.endpoints.web.exposure.include=health,info,metrics

spring.config.import=optional:configserver:${HOST_CONFIG:http://localhost}:8888