spring.application.name=authService
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
server.port=8081
spring.data.mongodb.uri=mongodb://${MONGO_USER:root}:${MONGO_PASSWORD:root}@mongodb:27017/auth_db_test?authSource=admin
eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90
logging.level.com.onlinebank.authService=INFO
logging.level.org.springframework.security=INFO
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.error.path=/error
spring.mvc.throw-exception-if-no-handler-found=true
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION:3600000}
app.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

