# ======================
# Application Basics
# ======================
spring.application.name=gatewayService
server.port=8080
spring.main.web-application-type=reactive

# ======================
# Spring Profiles
# ======================
spring.profiles.active=${PROFIL:local}

# ======================
# Config Server
# ======================
spring.config.import=optional:configserver:${HOST_CONFIG:http://localhost}:8888

# ======================
# Actuator
# ======================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

#http://localhost:8080/swagger-ui/index.html
#http://localhost:8080/swagger-ui/webjars/swagger-ui/index.html#/
