# ======================
# Application Basics
# ======================
spring.application.name=configService
server.port=8888

# ======================
# Spring Profiles
# ======================
spring.profiles.active=${PROFIL:local}

# Active le backend natif (filesystem/classpath) du Config Server
# OBLIGATOIRE — sans ça Spring Cloud cherche un repo Git
spring.profiles.include=native

# ======================
# Spring Cloud Config Server
# ======================
spring.cloud.config.server.native.search-locations=classpath:/config

# ======================
# Eureka Client
# ======================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# ======================
# Actuator
# ======================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always