# ======================
# Eureka - Local
# ======================
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

# ======================
# Logging
# ======================
logging.level.org.springframework.cloud.config=DEBUG
logging.level.com.netflix.eureka=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# ======================
# Actuator
# ======================
management.endpoints.web.base-path=/actuator