# src/main/resources/application-test.properties
spring.config.activate.on-profile=test

# Port
server.port=8761

# Configuration Eureka - Test (Docker)
eureka.instance.hostname=service-discovery
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/

# Activer la protection pour test
eureka.server.enable-self-preservation=true
eureka.server.renewal-percent-threshold=0.85

# Logging niveau INFO pour test
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO

# Actuator exposé pour Docker
management.endpoints.web.exposure.include=health,info,metrics,prometheus