# src/main/resources/application.properties
spring.application.name=discoveryService

# Configuration Eureka commune
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Le profil est défini par la variable d'environnement PROFIL
spring.profiles.active=${PROFIL:local}

# Configuration commune
management.endpoints.web.exposure.include=health,info,metrics
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n