# src/main/resources/application-local.properties


# Port
server.port=8761

# Configuration Eureka - Local
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Désactiver la protection pour le développement local
eureka.server.enable-self-preservation=false

# Logging niveau DEBUG pour local
logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG

# Actuator
management.endpoints.web.base-path=/actuator